spring:
  profiles.active: dev
       
#mybatis:
#  type-aliases-package: com.skcc.naruback.mapper
#  mapper-locations: mybatis/mapper/**/*.xml
#  config-location: classpath:/mybatis/mybatis-config.xml
       
---
spring:
  config.activate.on-profile: dev
  #profiles: dev
  naru:
    datasource:
      #jdbc-url: jdbc:mariadb://150.206.10.180:3306/narud?characterEncoding=UTF-8&autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
      #username: naru
      #password: skccmis!
      jdbc-url: jdbc:mariadb://34.64.198.41:3306/metaportal?characterEncoding=UTF-8&autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
      username: root
      password: skccmis!
      driver-class-name: org.mariadb.jdbc.Driver
      validationQuery: select 1
  eigw:
    datasource:
     # jdbc-url: jdbc:oracle:thin:@150.2.225.54:1507:EGWP2
      #username: egw
      #password: eigw_2016
      jdbc-url: jdbc:oracle:thin://34.64.198.41:1507:EGWP2
      username: root
      password: skccmis!
      driver-class-name: oracle.jdbc.driver.OracleDriver
      validationQuery: select 1
      
  quartz:
#    jobStore:
#      isClustered: true
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 3
#          plugin:
#            shutdownhook:
#              class: org.quartz.plugins.management.ShutdownHookPlugin
#              cleanShutdown: true
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            isClustered: true

#logging:
#  config: classpath:logback-spring-debug.xml

server:
  port: 3000
  servlet.session.timeout: 5400
 
  
  
---

spring:
  config.activate.on-profile: production
  #profiles: production 
  application:
    name: SpringBootJdbc
#  batch.job.enabled: false
  datasource: 
    url: jdbc:mysql://localhost:3316/metaportal
    username: metaportal
    password: skccmis!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

#logging:
#  config: classpath:logback-spring-debug.xml

server:
  port: 3000 